services:
  - type: web
    name: ipl-prediction-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CORS_ORIGINS
        value: "http://localhost:3000,https://your-frontend-domain.com"
      - key: ALLOW_CREDENTIALS
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/backend
      sizeGB: 5
    healthCheckPath: /health
    autoDeploy: true 