services:
  - type: web
    name: ipl-prediction-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: CORS_ORIGINS
        value: "http://localhost:3000,https://your-frontend-domain.com"
      - key: ALLOW_CREDENTIALS
        value: "true" 